source "http://rubygems.org"

  gem "rails", "2.3.2"
  gem "fastercsv", "1.1"
  gem "rtf"
  gem "sqlite3"
  gem "json"
  gem "comma"
  gem "paperclip", "~>2.3.1.1"
  gem "capistrano", "2.5.5"
  gem "passenger", "2.2.2"
  gem "tmail", "1.2.7.1"
